name: Local-ARC-Runner-gh-app-auth-Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: [arc-runner-set-local,arc-runner-set-local-gh-app]
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
